### 회원별 포인트 사용
POST http://localhost:8500/api/v1/points/1/deduct
Content-Type: application/json

{
  "uuid": "3653b24a-977b-4545-9811-fe1ce5be0511",
  "point": 5500
}

### 회원별 포인트 사용
POST http://localhost:8500/api/v1/points/1/deduct
Content-Type: application/json

{
  "uuid": "3653b24a-977b-4545-9811-fe1ce5be0512",
  "point": 3400
}

### 회원별 포인트 사용
POST http://localhost:8500/api/v1/points/1/deduct
Content-Type: application/json

{
  "uuid": "3653b24a-977b-4545-9811-fe1ce5be0513",
  "point": 8000
}
