name: Notify Unreviewed PRs

on:
  schedule:
    - cron: '0 1 * * 1-5'  # UTC 기준으로는 매일 1시에 실행, 한국 시간으로는 월요일~금요일까지 아침 10시에 해당한다.
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install requests

    - name: Notify Unreviewed PRs
      run: |
        cd point/.github/workflows  # 스크립트가 있는 디렉토리로 이동
        python notify_prs.py
      env:
        SLACK_WEBHOOK_URL: TEST
        REPOSITORY_OWNER: seolys
        REPOSITORY_NAME: point
